@echo off
title MineLauncher
set dir=%AppData%\.minecraft
set bin=%AppData%\.minecraft\bin
set run=%AppData%\.minecraft\runtime\bin
set nat=%AppData%\.minecraft\natives
set ast=%AppData%\.minecraft\assets
set lib=%AppData%\.minecraft\libraries
set usr=Игрок
set ram=1024
"%bin%\cmdow.exe" @ /HID
"%run%\javaw.exe" -Xms%ram%G -Xmx%ram%G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe.heapdump -Dos.name="Windows 10" -Dminecraft.launcher.brand="cms" -Dminecraft.launcher.version=2.3 -Dlog4j.configurationFile="%ast%\log_configs\client-1.12.xml" -Djava.library.path="%nat%" -cp "%lib%\com\google\code\gson\gson\2.8.0\gson-2.8.0.jar;%lib%\com\google\guava\guava\21.0\guava-21.0.jar;%lib%\com\ibm\icu\icu4j-core-mojang\51.2\icu4j-core-mojang-51.2.jar;%lib%\com\mojang\authlib\1.5.25\authlib-1.5.25.jar;%lib%\com\mojang\authlib\1.5.25\authlib-1.5.25.jar;%lib%\com\mojang\brigadier\1.0.17\brigadier-1.0.17.jar;%lib%\com\mojang\datafixerupper\2.0.24\datafixerupper-2.0.24.jar;%lib%\com\mojang\javabridge\1.0.22\javabridge-1.0.22.jar;%lib%\com\mojang\patchy\1.1\patchy-1.1.jar;%lib%\com\mojang\text2speech\1.11.3\text2speech-1.11.3.jar;%lib%\commons-codec\commons-codec\1.10\commons-codec-1.10.jar;%lib%\commons-io\commons-io\2.5\commons-io-2.5.jar;%lib%\commons-logging\commons-logging\1.1.3\commons-logging-1.1.3.jar;%lib%\io\netty\netty-all\4.1.25.Final\netty-all-4.1.25.Final.jar;%lib%\it\unimi\dsi\fastutil\8.2.1\fastutil-8.2.1.jar;%lib%\net\java\dev\jna\jna\4.4.0\jna-4.4.0.jar;%lib%\net\java\dev\jna\platform\3.4.0\platform-3.4.0.jar;%lib%\net\java\jinput\jinput\2.0.5\jinput-2.0.5.jar;%lib%\net\java\jutils\jutils\1.0.0\jutils-1.0.0.jar;%lib%\net\sf\jopt-simple\jopt-simple\5.0.3\jopt-simple-5.0.3.jar;%lib%\optifine\launchwrapper-of\2.1\launchwrapper-of-2.1.jar;%lib%\optifine\OptiFine\1.14.4_HD_U_F5\OptiFine-1.14.4_HD_U_F5.jar;%lib%\org\apache\commons\commons-compress\1.8.1\commons-compress-1.8.1.jar;%lib%\org\apache\commons\commons-lang3\3.5\commons-lang3-3.5.jar;%lib%\org\apache\httpcomponents\httpclient\4.3.3\httpclient-4.3.3.jar;%lib%\org\apache\httpcomponents\httpcore\4.3.2\httpcore-4.3.2.jar;%lib%\org\apache\logging\log4j\log4j-api\2.8.1\log4j-api-2.8.1.jar;%lib%\org\apache\logging\log4j\log4j-core\2.8.1\log4j-core-2.8.1.jar;%lib%\org\lwjgl\lwjgl\3.2.2\lwjgl-3.2.2.jar;%lib%\org\lwjgl\lwjgl-glfw\3.2.2\lwjgl-glfw-3.2.2.jar;%lib%\org\lwjgl\lwjgl-jemalloc\3.2.2\lwjgl-jemalloc-3.2.2.jar;%lib%\org\lwjgl\lwjgl-openal\3.2.2\lwjgl-openal-3.2.2.jar;%lib%\org\lwjgl\lwjgl-opengl\3.2.2\lwjgl-opengl-3.2.2.jar;%lib%\org\lwjgl\lwjgl-stb\3.2.2\lwjgl-stb-3.2.2.jar;%lib%\oshi-project\oshi-core\1.1\oshi-core-1.1.jar;%lib%\net\minecraft\client\1.14.4-OptiFine_HD_U_F5\1.14.4-OptiFine_HD_U_F5.jar" net.minecraft.launchwrapper.Launch --username "%usr%" --version 1.14.4-OptiFine_HD_U_F5 --gameDir "%dir%" --assetsDir "%ast%" --assetIndex 1.14 --uuid null --accessToken null --userType mojang --versionType release --tweakClass optifine.OptiFineTweaker
del "%dir%\logs\*.gz"
exit